finish

diff --git a/srcs/requirements/nginx/Dockerfile b/srcs/requirements/nginx/Dockerfile
--- a/srcs/requirements/nginx/Dockerfile
+++ b/srcs/requirements/nginx/Dockerfile
@@ -1,17 +1,51 @@
 FROM debian:bullseye
 
-WORKDIR /app
+LABEL author="isadri"
 
-RUN apt-get update && apt-get upgrade -y && apt-get install -y nginx
-RUN apt-get install -y vim && apt-get install -y openssl
-
-RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-	-keyout /etc/ssl/private/nginx_selfsigned.key \
-	-out /etc/ssl/certs/nginx_selfsigned.crt    \
-	-subj "/C=MO/L=KH/O=1337FIL/OU=IT/CN=iabkadri.42.ma"
-
+# our application will use the port 443
 EXPOSE 443
 
-COPY conf/default.conf /etc/nginx/sites-available/default
+# set /app as the working directory of the container
+WORKDIR /app
 
-CMD ["nginx", "-g", "daemon off;"]
+#ENV DOMAIN_NAME=isadri.42.fr \
+#	KEY=/etc/ssl/private/nginx-selfsigned.key \
+#	CERT=/etc/ssl/certs/nginx-selfsigned.crt
+
+
+# set variable that hold the path of the certificate and the private key
+#ENV KEY=/etc/ssl/private/nginx-selfsigned.key \
+#	CERT=/etc/ssl/certs/nginx-selfsigned.crt \
+#	DOMAIN_NAME=isadri.42.fr
+
+# install dependencies
+RUN apt-get update ; apt-get install --no-install-recommends -y nginx vim \
+	openssl iputils-ping
+
+# create the certificate and generate the private key
+RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
+	-keyout /etc/ssl/private/nginx-selfsigned.key -out \
+	 /etc/ssl/certs/nginx-selfsigned.crt -subj "/CN=${DOMAIN_NAME}"
+
+# openssl:	This is the basic command line tool for creating and managing OpenSSL certificates,
+# 			keys, and other files.
+# req:	specifies which certicate we want to use.
+# -x509:	specifies that we want to make a self-signed certificate.
+# -nodes:	skip the option to secure our certificate with a passphrase.
+# -days 365:	sets the length of time that the certificate will be considered valid.
+# -newkey rsa:2048:	generate a new certificate and a new key at the same time.
+#					And the rsa:2048 portion make an RSA key that is 2048 bits long.
+# -keyout:	where to place the generated private key file.
+# -out:	where to place the certificate.
+# -subj: fill the common name option by ${DOMAIN_NAME}
+
+# copy my nginx configuration to the container
+#COPY conf/nginx.conf /etc/nginx/sites-available/default
+COPY conf/nginx.conf /etc/nginx/conf.d/
+
+# wait untils wordpress service is started
+#HEALTHCHECK --interval=5s --retries=2 \
+#			CMD [ "ping", "wordpress" ] || exit 1
+
+# run nginx in the foreground
+CMD [ "nginx", "-g", "daemon off;" ]
diff --git a/srcs/requirements/wordpress/Dockerfile b/srcs/requirements/wordpress/Dockerfile
--- a/srcs/requirements/wordpress/Dockerfile
+++ b/srcs/requirements/wordpress/Dockerfile
@@ -1,16 +1,44 @@
 FROM debian:bullseye
 
+LABEL author="isadri"
+
+# change working directory
 WORKDIR /var/www/html
 
-RUN apt-get update && apt-get install vim curl unzip iputils-ping -y
-RUN apt-get install -y php php-curl php-zip php-mysqlnd php-intl php-fpm
-RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
-    && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
+EXPOSE 9000
 
-RUN wp core download --allow-root
+#ENV MYSQL_DATABASE=wp-db \
+#	MYSQL_USER=db-user \
+#	MYSQL_PASSWORD=123456 \
+#	MYSQL_ROOT=root \
+#	MYSQL_ROOT_PASSWORD=root123 \
+#	MYSQL_HOST=mariadb:3306 \
+#	DOMAIN_NAME=isadri.42.fr
 
-COPY script.sh .
 
-#RUN bash script.sh
+# install dependencies
+#RUN apt-get update ; apt-get install -y curl php php-curl php-mysqlnd php-intl \
+#	php-zip php-fpm iputils-ping
 
-CMD ["bash", "script.sh"]
+RUN apt-get update ; apt-get install -y curl php7.4-mysql \
+	php7.4-fpm iputils-ping
+
+# install wp-cli
+RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar ; \
+	chmod +x wp-cli.phar ; mv wp-cli.phar /usr/local/bin/wp
+
+# wait until mariadb service is started
+#HEALTHCHECK --interval=5s --retries=2 \
+#			CMD [ "ping", "mariadb" ] || exit 1
+
+# copy php-fpm configuration
+COPY tools/www.conf /etc/php/7.4/fpm/pool.d/www.conf
+#COPY tools/www.conf .
+
+# copy script to launch
+COPY tools/docker-wordpress-entrypoint.sh .
+
+ENTRYPOINT [ "bash", "docker-wordpress-entrypoint.sh" ]
+
+#CMD [ "bash" ]
+CMD [ "/usr/sbin/php-fpm7.4", "-F" ]
